import type { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    name: 'Premium Soy Wax',
    description: 'High-quality 100% natural soy wax flakes, perfect for container candles. Burns clean and slow with excellent fragrance throw. Ideal for beginners and professionals alike.',
    price: 950,
    unit: '500g',
    category: 'wax',
    stock: 5000, // grams
    images: ['https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&auto=format'],
    minOrder: 1,
    featured: true,
    priceTiers: [
      { label: '500g', qty: 500, inputUnit: 'g', price: 950, isBulk: false },
      { label: '1 kg+', qty: 1, inputUnit: 'kg', price: 1750, isBulk: true },
    ],
    allowDecimal: true,
  },
  {
    id: 'mock-2',
    name: 'Coconut Wax Blend',
    description: 'Premium coconut wax blend for superior scent throw and creamy appearance. Creates beautiful, smooth candle tops with a luxurious finish.',
    price: 1350,
    unit: '500g',
    category: 'wax',
    stock: 3000, // grams
    images: ['https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&auto=format'],
    minOrder: 1,
    featured: true,
    priceTiers: [
      { label: '500g', qty: 500, inputUnit: 'g', price: 1350, isBulk: false },
      { label: '1 kg+', qty: 1, inputUnit: 'kg', price: 2500, isBulk: true },
    ],
    allowDecimal: true,
  },
  {
    id: 'mock-3',
    name: 'Paraffin Wax',
    description: 'Food-grade refined paraffin wax suitable for pillar and taper candles. Excellent clarity and gloss finish.',
    price: 250,
    unit: '250g',
    category: 'wax',
    stock: 8000, // grams
    images: ['https://images.unsplash.com/photo-1603905030530-e08e85b77b5a?w=600&auto=format'],
    minOrder: 1,
    featured: false,
    priceTiers: [
      { label: '250g', qty: 250, inputUnit: 'g', price: 250, isBulk: false },
      { label: '500g', qty: 500, inputUnit: 'g', price: 440, isBulk: false },
      { label: '1 kg+', qty: 1, inputUnit: 'kg', price: 800, isBulk: true },
    ],
    allowDecimal: true,
  },
  {
    id: 'mock-4',
    name: 'Beeswax Pellets',
    description: 'Natural filtered beeswax pellets with a subtle honey aroma. Slow-burning and ideal for beeswax pillar and taper candles.',
    price: 1800,
    unit: '250g',
    category: 'wax',
    stock: 2000, // grams
    images: ['https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=600&auto=format'],
    minOrder: 1,
    featured: false,
    priceTiers: [
      { label: '250g', qty: 250, inputUnit: 'g', price: 1800, isBulk: false },
      { label: '500g', qty: 500, inputUnit: 'g', price: 3400, isBulk: false },
      { label: '1 kg+', qty: 1, inputUnit: 'kg', price: 6500, isBulk: true },
    ],
    allowDecimal: true,
  },
  {
    id: 'mock-5',
    name: 'Lavender Fields Fragrance Oil',
    description: 'A calming blend of fresh lavender with subtle floral notes. Blends beautifully with soy and coconut wax. Recommended usage: 6–10% of wax weight.',
    price: 480,
    unit: '50ml',
    category: 'fragrance',
    stock: 2500, // ml
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&auto=format'],
    minOrder: 1,
    featured: true,
    weightGrams: 0.9, // g per ml
    priceTiers: [
      { label: '50ml', qty: 50, inputUnit: 'ml', price: 480, isBulk: false },
      { label: '100ml', qty: 100, inputUnit: 'ml', price: 780, isBulk: false },
      { label: '250ml+', qty: 250, inputUnit: 'ml', price: 1750, isBulk: false },
    ],
    allowDecimal: false,
  },
  {
    id: 'mock-6',
    name: 'Vanilla Bean Fragrance Oil',
    description: 'Rich, warm vanilla with creamy caramel undertones. A bestselling scent with excellent hot and cold throw in all wax types.',
    price: 480,
    unit: '50ml',
    category: 'fragrance',
    stock: 3000, // ml
    images: ['https://images.unsplash.com/photo-1575663159592-bce97f2a8a11?w=600&auto=format'],
    minOrder: 1,
    featured: true,
    weightGrams: 0.9,
    priceTiers: [
      { label: '50ml', qty: 50, inputUnit: 'ml', price: 480, isBulk: false },
      { label: '100ml', qty: 100, inputUnit: 'ml', price: 780, isBulk: false },
      { label: '250ml+', qty: 250, inputUnit: 'ml', price: 1750, isBulk: false },
    ],
    allowDecimal: false,
  },
  {
    id: 'mock-7',
    name: 'Rose & Oud Fragrance Oil',
    description: 'Luxurious blend of fresh rose petals with warm oud wood base. An elegant, long-lasting fragrance for premium candles.',
    price: 580,
    unit: '50ml',
    category: 'fragrance',
    stock: 1500, // ml
    images: ['https://images.unsplash.com/photo-1592136957897-b2b6ca21e10d?w=600&auto=format'],
    minOrder: 1,
    featured: true,
    weightGrams: 0.9,
    priceTiers: [
      { label: '50ml', qty: 50, inputUnit: 'ml', price: 580, isBulk: false },
      { label: '100ml', qty: 100, inputUnit: 'ml', price: 980, isBulk: false },
      { label: '250ml+', qty: 250, inputUnit: 'ml', price: 2200, isBulk: false },
    ],
    allowDecimal: false,
  },
  {
    id: 'mock-8',
    name: 'Citrus Burst Fragrance Oil',
    description: 'Bright and energising blend of orange, lemon, and grapefruit. Perfect for creating refreshing summer candles.',
    price: 420,
    unit: '50ml',
    category: 'fragrance',
    stock: 2000, // ml
    images: ['https://images.unsplash.com/photo-1590112073695-04f3efb40b59?w=600&auto=format'],
    minOrder: 1,
    featured: false,
    weightGrams: 0.9,
    priceTiers: [
      { label: '50ml', qty: 50, inputUnit: 'ml', price: 420, isBulk: false },
      { label: '100ml', qty: 100, inputUnit: 'ml', price: 680, isBulk: false },
      { label: '250ml+', qty: 250, inputUnit: 'ml', price: 1500, isBulk: false },
    ],
    allowDecimal: false,
  },
  {
    id: 'mock-9',
    name: 'Cotton Wicks #4 (Natural)',
    description: 'Pre-waxed cotton wicks with sustainer tabs. Suitable for containers 5–7cm diameter. Pack of 50 wicks. Clean burn with minimal mushrooming.',
    price: 450,
    unit: 'pack/50',
    category: 'wicks',
    stock: 300,
    weightGrams: 150,
    images: ['https://images.unsplash.com/photo-1605651377661-7b39b5cb0a7f?w=600&auto=format'],
    minOrder: 1,
    featured: true,
  },
  {
    id: 'mock-10',
    name: 'Cotton Wicks #6 (Natural)',
    description: 'Pre-waxed cotton wicks with sustainer tabs. Suitable for containers 7–9cm diameter. Pack of 50 wicks.',
    price: 480,
    unit: 'pack/50',
    category: 'wicks',
    stock: 250,
    weightGrams: 150,
    images: ['https://images.unsplash.com/photo-1605651377661-7b39b5cb0a7f?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-11',
    name: 'Wooden Wick Set',
    description: 'Natural wood crackling wicks for a cosy fireplace effect. Includes 20 wicks with metal tabs. Works best with soy and coconut wax.',
    price: 680,
    unit: 'pack/20',
    category: 'wicks',
    stock: 120,
    weightGrams: 100,
    images: ['https://images.unsplash.com/photo-1603905030530-e08e85b77b5a?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-12',
    name: 'Candle Dye Chips — Red',
    description: 'Concentrated dye chips for vibrant, consistent colour. A little goes a long way — one chip colours approx. 500g of wax. Solvent-free and non-toxic.',
    price: 320,
    unit: '10 chips',
    category: 'dye',
    stock: 180,
    weightGrams: 30,
    images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-13',
    name: 'Candle Dye Chips — Ivory',
    description: 'Subtle ivory/cream dye for a natural, elegant finish. Perfect for vanilla and floral scented candles.',
    price: 320,
    unit: '10 chips',
    category: 'dye',
    stock: 200,
    weightGrams: 30,
    images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-14',
    name: 'Clear Glass Jar — 200ml',
    description: 'Smooth-sided clear glass jar with straight walls. Perfect for showcasing coloured or layered candles. Lid sold separately.',
    price: 185,
    unit: 'piece',
    category: 'containers',
    stock: 500,
    weightGrams: 200,
    images: ['https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=600&auto=format'],
    minOrder: 6,
    featured: true,
  },
  {
    id: 'mock-15',
    name: 'Amber Glass Jar — 300ml',
    description: 'Elegant amber glass jar with a premium feel. Excellent UV protection. Suitable for all wax types.',
    price: 280,
    unit: 'piece',
    category: 'containers',
    stock: 300,
    weightGrams: 300,
    images: ['https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&auto=format'],
    minOrder: 6,
    featured: false,
  },
  {
    id: 'mock-16',
    name: 'Aluminium Tin — 150ml',
    description: 'Matte silver aluminium tin with press-on lid. Lightweight, travel-friendly and ideal for gift candles.',
    price: 120,
    unit: 'piece',
    category: 'containers',
    stock: 400,
    weightGrams: 50,
    images: ['https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=600&auto=format'],
    minOrder: 12,
    featured: false,
  },
  {
    id: 'mock-17',
    name: 'Digital Candle Thermometer',
    description: 'Stainless steel probe thermometer with instant-read display. Essential for monitoring wax pour temperature for optimal fragrance binding.',
    price: 1450,
    unit: 'piece',
    category: 'tools',
    stock: 40,
    weightGrams: 100,
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-18',
    name: 'Stainless Pour Pitcher — 1L',
    description: 'Heavy-duty stainless steel pouring pitcher with heat-resistant handle and precision spout. Holds up to 1L of melted wax.',
    price: 1850,
    unit: 'piece',
    category: 'tools',
    stock: 35,
    weightGrams: 450,
    images: ['https://images.unsplash.com/photo-1575663159592-bce97f2a8a11?w=600&auto=format'],
    minOrder: 1,
    featured: false,
  },
  {
    id: 'mock-19',
    name: 'Beginner Candle Making Kit',
    description: 'Everything you need to make your first 4 candles. Includes 500g soy wax, 2 fragrance oils (50ml each), 10 wicks, 4 glass jars, thermometer guide, and step-by-step instructions.',
    price: 3850,
    unit: 'kit',
    category: 'kits',
    stock: 25,
    weightGrams: 1500,
    images: ['https://images.unsplash.com/photo-1592136957897-b2b6ca21e10d?w=600&auto=format'],
    minOrder: 1,
    featured: true,
  },
  {
    id: 'mock-20',
    name: 'Advanced Candle Kit',
    description: 'For the serious crafter. Includes 1kg coconut wax, 3 premium fragrance oils (100ml each), wooden & cotton wicks, amber jars, dye chips, pour pitcher, and thermometer.',
    price: 7200,
    unit: 'kit',
    category: 'kits',
    stock: 15,
    weightGrams: 2800,
    images: ['https://images.unsplash.com/photo-1590112073695-04f3efb40b59?w=600&auto=format'],
    minOrder: 1,
    featured: true,
  },

  // ── Packaging / internal items ────────────────────────────────────────────
  {
    id: 'pkg-001',
    name: 'Small Kraft Gift Box',
    description: 'Single-candle kraft box, 8 × 8 × 9 cm. Suitable for up to 200ml containers.',
    price: 45,
    unit: 'piece',
    category: 'packaging',
    stock: 300,
    images: [],
    minOrder: 1,
    featured: false,
    isPackaging: true,
    weightGrams: 30,
  },
  {
    id: 'pkg-002',
    name: 'Medium Kraft Gift Box',
    description: 'Two-candle kraft box, 18 × 10 × 10 cm. Fits two standard jar candles.',
    price: 75,
    unit: 'piece',
    category: 'packaging',
    stock: 200,
    images: [],
    minOrder: 1,
    featured: false,
    isPackaging: true,
    weightGrams: 55,
  },
  {
    id: 'pkg-003',
    name: 'Bubble Wrap Sheet',
    description: '30 × 30 cm bubble wrap sheet for wrapping fragile items.',
    price: 8,
    unit: 'sheet',
    category: 'packaging',
    stock: 1000,
    images: [],
    minOrder: 1,
    featured: false,
    isPackaging: true,
  },
  {
    id: 'pkg-004',
    name: 'Tissue Paper Sheet',
    description: 'Premium tissue paper sheet for product wrapping, 50 × 70 cm.',
    price: 5,
    unit: 'sheet',
    category: 'packaging',
    stock: 2000,
    images: [],
    minOrder: 1,
    featured: false,
    isPackaging: true,
  },
  {
    id: 'pkg-005',
    name: 'Thank You Card',
    description: 'Branded Candle Heaven thank you card included with every order.',
    price: 12,
    unit: 'piece',
    category: 'packaging',
    stock: 500,
    images: [],
    minOrder: 1,
    featured: false,
    isPackaging: true,
  },
];
